name: Testing

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    steps:
      - name: Check Python version 
        run: |
          python3 --version
          ls -la
      # - name: Run Tests
      #   run: |
        
      #     cd 'assignment_4/'
      #     python3 -m unittest discover -s 'tests/' -p '*_test.py'