name: Testing

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install deps
        run: |
          pip3 install -r requirements.txt
      - name: Run Tests
        run: |
          python3 -m unittest discover -s assignment_3 -p '*_test.py'
          python3 -m unittest discover -s assignment_4 -p '*_test.py'
      - name: Run Linting
        run: |
          cd ..
          pycodestyle ZP_1/
